#!/usr/bin/env ruby
#
# This file was generated by Bundler.
#
# The application 'rspec' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'pathname'
ENV['BUNDLE_GEMFILE'] ||= File.expand_path("../../Gemfile",
  Pathname.new(__FILE__).realpath)

require 'rubygems'
require 'bundler/setup'

require 'yaml'
require 'hashdiff'
require 'colorize'

def usage
  puts "script/compare-yaml <yaml_file>"
  abort
end

usage unless ARGV[0]

application_config = YAML.load_file('config/constants.yml')

example_config = YAML.load_file(ARGV[0])


application_config_keys = application_config.keys

example_config_keys = example_config.keys

hash = Hash.new
application_config_keys.each do |key|
  if example_config_keys.include? key
    hash[key] = example_config[key]
  else
    hash[key] = application_config[key]
  end
end

File.open('tmp/my-constants.yml', 'w') { |file| file.write(hash.to_yaml) }

puts HashDiff.diff(application_config, hash)
