#!/usr/bin/env ruby

require File.expand_path('../../config/environment',  __FILE__)

require 'active_record'
require 'json'
require 'uri'
require 'colorize'

def beautify_json(json)
  JSON.pretty_generate(JSON.parse(json))
end

File.open('tmp/settings.json', 'w') { |file| file.write(beautify_json(Setting.all.to_json)) }
